/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthButton: typeof import('./components/auth/Button.vue')['default']
    AuthProfile: typeof import('./components/auth/Profile.vue')['default']
    AuthSignInModal: typeof import('./components/auth/SignInModal.vue')['default']
    AuthSignUpModal: typeof import('./components/auth/SignUpModal.vue')['default']
    BaseButtonButton: typeof import('./components/base/Button/Button.vue')['default']
    BaseCheckboxCheckbox: typeof import('./components/base/Checkbox/Checkbox.vue')['default']
    BaseChipChip: typeof import('./components/base/Chip/Chip.vue')['default']
    BaseCircularIconButtonCircularIconButton: typeof import('./components/base/CircularIconButton/CircularIconButton.vue')['default']
    BaseDividerDivider: typeof import('./components/base/Divider/Divider.vue')['default']
    BaseDropdownDropdown: typeof import('./components/base/Dropdown/Dropdown.vue')['default']
    BaseInputInput: typeof import('./components/base/Input/Input.vue')['default']
    BaseLinkLink: typeof import('./components/base/Link/Link.vue')['default']
    BaseLoaderLoader: typeof import('./components/base/Loader/Loader.vue')['default']
    BaseModalModal: typeof import('./components/base/Modal/Modal.vue')['default']
    BaseTextareaTextarea: typeof import('./components/base/Textarea/Textarea.vue')['default']
    BaseTypeaheadTypeahead: typeof import('./components/base/Typeahead/Typeahead.vue')['default']
    BaseTypographyTypography: typeof import('./components/base/Typography/Typography.vue')['default']
    CategoryTabsIconAppetizer: typeof import('./components/category-tabs/icon/appetizer.vue')['default']
    CategoryTabsIconMexican: typeof import('./components/category-tabs/icon/mexican.vue')['default']
    CategoryTabsIconPasta: typeof import('./components/category-tabs/icon/pasta.vue')['default']
    CategoryTabsIconPizza: typeof import('./components/category-tabs/icon/pizza.vue')['default']
    CategoryTabsIconSalad: typeof import('./components/category-tabs/icon/salad.vue')['default']
    CategoryTabsIconSauce: typeof import('./components/category-tabs/icon/sauce.vue')['default']
    CategoryTabsIconSidedish: typeof import('./components/category-tabs/icon/sidedish.vue')['default']
    CategoryTabsIconSoup: typeof import('./components/category-tabs/icon/soup.vue')['default']
    CategoryTabsIconSushi: typeof import('./components/category-tabs/icon/sushi.vue')['default']
    CategoryTabsItem: typeof import('./components/category-tabs/item.vue')['default']
    CategoryTabsList: typeof import('./components/category-tabs/list.vue')['default']
    EditRecipeAddIngredientModal: typeof import('./components/edit-recipe/AddIngredientModal.vue')['default']
    EditRecipeAddStepModal: typeof import('./components/edit-recipe/AddStepModal.vue')['default']
    ImageCloudinary: typeof import('./components/image/Cloudinary.vue')['default']
    LayoutContainer: typeof import('./components/layout/Container.vue')['default']
    LayoutHeader: typeof import('./components/layout/Header.vue')['default']
    LayoutPageLoader: typeof import('./components/layout/PageLoader.vue')['default']
    RecipeDetailsHeroImage: typeof import('./components/recipe-details/HeroImage.vue')['default']
    RecipesListDeleteRecipeModal: typeof import('./components/recipes-list/DeleteRecipeModal.vue')['default']
    RecipesListFilterModal: typeof import('./components/recipes-list/filter-modal.vue')['default']
    RecipesListGrid: typeof import('./components/recipes-list/Grid.vue')['default']
    RecipesListItem: typeof import('./components/recipes-list/Item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingListShoppingList: typeof import('./components/shopping-list/ShoppingList.vue')['default']
    ShoppingListShoppingListAddItemField: typeof import('./components/shopping-list/ShoppingListAddItemField.vue')['default']
    ShoppingListShoppingListItem: typeof import('./components/shopping-list/ShoppingListItem.vue')['default']
  }
}
